"use client";

import { useMemo, useState } from "react";

type View = "overview" | "devices" | "tokens" | "approvals" | "audit" | "settings";
type Status = "运行中" | "即将到期" | "已锁定" | "时钟异常" | "永久解锁";
type Device = { sn:string; site:string; customer:string; product:"CH3"|"CH2"; status:Status; days:number|null; expiry:string; mode:string; online:boolean; soc:number };

const devices:Device[]=[
  {sn:"CH3ZA26071408",site:"Cape Town Cold Storage",customer:"Ubuntu Energy Leasing",product:"CH3",status:"即将到期",days:2,expiry:"2026-07-30",mode:"限制储能服务",online:false,soc:68},
  {sn:"CH2ZA26060317",site:"Johannesburg Retail Hub",customer:"Mandla Power Services",product:"CH2",status:"运行中",days:43,expiry:"2026-09-09",mode:"完全停止输出",online:true,soc:81},
  {sn:"CH3BW26052504",site:"Gaborone Textile Plant",customer:"Kalahari Asset Co.",product:"CH3",status:"已锁定",days:0,expiry:"2026-07-25",mode:"限制储能服务",online:false,soc:24},
  {sn:"CH2ZA26041826",site:"Durban Food Processing",customer:"Ubuntu Energy Leasing",product:"CH2",status:"时钟异常",days:18,expiry:"2026-08-15",mode:"限制储能服务",online:true,soc:56},
  {sn:"CH3NA26032909",site:"Windhoek Business Park",customer:"NamSun Finance",product:"CH3",status:"运行中",days:72,expiry:"2026-10-08",mode:"完全停止输出",online:true,soc:73},
  {sn:"CH2ZA26020611",site:"Pretoria Medical Centre",customer:"Mandla Power Services",product:"CH2",status:"永久解锁",days:null,expiry:"永久",mode:"限制储能服务",online:true,soc:92},
];
const nav:{id:View;label:string;icon:string;badge?:string}[]=[
  {id:"overview",label:"运营总览",icon:"⌂"},{id:"devices",label:"设备资产",icon:"▦",badge:"1.2k"},
  {id:"tokens",label:"Token 中心",icon:"◇"},{id:"approvals",label:"审批中心",icon:"✓",badge:"3"},
  {id:"audit",label:"审计日志",icon:"≡"},{id:"settings",label:"策略配置",icon:"⚙"},
];
const tone=(s:Status)=>({"运行中":"success","即将到期":"warning","已锁定":"danger","时钟异常":"purple","永久解锁":"neutral"}[s]);

export default function Home(){
  const [view,setView]=useState<View>("overview"),[query,setQuery]=useState(""),[filter,setFilter]=useState("全部状态");
  const [selected,setSelected]=useState<Device|null>(null),[tokenOpen,setTokenOpen]=useState(false),[token,setToken]=useState(""),[toast,setToast]=useState("");
  const filtered=useMemo(()=>devices.filter(d=>(d.sn+d.site+d.customer).toLowerCase().includes(query.toLowerCase())&&(filter==="全部状态"||d.status===filter)),[query,filter]);
  const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2400)};
  const go=(v:View)=>{setView(v);setSelected(null);window.scrollTo({top:0,behavior:"smooth"})};
  return <div className="shell">
    <aside className="side">
      <div className="brand"><span>S</span><div><b>SAJ CONTROL</b><small>PAYG 资产授权中心</small></div></div>
      <nav><p>管理工作台</p>{nav.slice(0,4).map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>go(n.id)}><i>{n.icon}</i><span>{n.label}</span>{n.badge&&<em>{n.badge}</em>}</button>)}<p>安全与系统</p>{nav.slice(4).map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>go(n.id)}><i>{n.icon}</i><span>{n.label}</span></button>)}</nav>
      <div className="system-ok"><b><i/>系统服务正常</b><small>Token 签名服务 · 在线</small></div>
      <div className="profile"><span>PL</span><div><b>Peng Li</b><small>渠道商管理员</small></div><button>•••</button></div>
    </aside>
    <main><header className="top"><div><span>南部非洲区域</span><b>/</b><strong>{nav.find(n=>n.id===view)?.label}</strong></div><section><button>?</button><button className="bell">●<i/></button><span className="avatar">PL</span><div><b>Peng Li</b><small>管理员</small></div></section></header>
      <div className="page">
        {view==="overview"&&<Overview go={go} create={()=>setTokenOpen(true)} select={setSelected} notify={notify}/>}
        {view==="devices"&&<Devices rows={filtered} query={query} filter={filter} setQuery={setQuery} setFilter={setFilter} select={setSelected} create={()=>setTokenOpen(true)}/>}
        {view==="tokens"&&<Tokens create={()=>setTokenOpen(true)} notify={notify}/>}
        {view==="approvals"&&<Approvals notify={notify}/>}
        {view==="audit"&&<Audit/>}
        {view==="settings"&&<Settings notify={notify}/>}
      </div>
    </main>
    {selected&&<Drawer device={selected} close={()=>setSelected(null)} create={()=>setTokenOpen(true)}/>}
    {tokenOpen&&<TokenModal token={token} close={()=>{setTokenOpen(false);setToken("")}} generate={()=>{setToken("7841 9256 0318 4472");notify("Token 已生成，并写入审计日志")}}/>}
    {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </div>
}

function Heading({tag,title,sub,actions}:{tag:string;title:string;sub:string;actions?:React.ReactNode}){return <div className="heading"><div><small>{tag}</small><h1>{title}</h1><p>{sub}</p></div>{actions&&<section>{actions}</section>}</div>}
function PanelHead({title,sub,action,onClick}:{title:string;sub:string;action?:string;onClick?:()=>void}){return <header className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button onClick={onClick}>{action} →</button>}</header>}

function Overview({go,create,select,notify}:{go:(v:View)=>void;create:()=>void;select:(d:Device)=>void;notify:(m:string)=>void}){
  const metrics=[["受管设备","1,284","+32 本月","blue","▦"],["7 天内到期","46","需跟进付款","amber","◷"],["当前已锁定","18","1.4% 设备","red","⊘"],["时钟异常","7","3 项将超宽限期","violet","⌁"]];
  return <><Heading tag="PAYG OPERATIONS" title="离线授权运营总览" sub="管理设备授权周期、锁机风险和 Token 发放，安全保护始终优先于商业控制。" actions={<><button className="secondary" onClick={()=>notify("运营报告已加入导出队列")}>导出报告</button><button className="primary" onClick={create}>＋ 生成 Token</button></>}/>
    <div className="safety"><span>安全原则</span><p>锁机不等于整机断电：BMS、消防、温控、保护性充电及本地解锁通道保持运行。</p><button onClick={()=>go("settings")}>查看策略 →</button></div>
    <div className="metrics">{metrics.map(m=><button key={m[0]} onClick={()=>go("devices")}><i className={m[3]}>{m[4]}</i><div><small>{m[0]}</small><b>{m[1]}</b><em>{m[2]}</em></div><span>↗</span></button>)}</div>
    <div className="dash-grid"><section className="panel distribution"><PanelHead title="授权状态分布" sub="共 1,284 台已启用 PAYG 的设备" action="查看设备" onClick={()=>go("devices")}/><div className="chart"><div className="donut"><span><b>1,284</b><small>受管设备</small></span></div><div className="legend">{[["正常运行","1,169","91.0%","green"],["即将到期","46","3.6%","yellow"],["已锁定","18","1.4%","red"],["永久解锁","44","3.4%","gray"],["异常宽限","7","0.6%","purple"]].map(x=><div key={x[0]}><i className={x[3]}/><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></div></section>
      <section className="panel attention"><PanelHead title="需要立即处理" sub="按风险等级排序"/><button onClick={()=>select(devices[3])}><i className="violet">⌁</i><span><b>3 台设备即将超出时钟异常宽限期</b><small>最短剩余 5 小时 · 需时间修复</small></span><em>高风险</em></button><button onClick={()=>select(devices[2])}><i className="red">⊘</i><span><b>Gaborone Textile Plant 已锁定</b><small>等待付款确认 · 已锁定 3 天</small></span><em>待处理</em></button><button onClick={()=>go("approvals")}><i className="amber">✓</i><span><b>2 个永久解锁申请等待审批</b><small>包含 1 个关键负载项目</small></span><em>需审批</em></button></section>
    </div>
    <section className="panel table-panel"><PanelHead title="到期与异常设备" sub="未来 7 天到期、已锁定及时间异常" action="全部设备" onClick={()=>go("devices")}/><DeviceTable rows={[devices[0],devices[2],devices[3],devices[1]]} select={select}/></section>
  </>
}

function DeviceTable({rows,select}:{rows:Device[];select:(d:Device)=>void}){return <div className="table-wrap"><table><thead><tr><th>设备 / 站点</th><th>客户</th><th>授权状态</th><th>剩余</th><th>到期日期</th><th>连接</th><th>锁机模式</th><th/></tr></thead><tbody>{rows.map(d=><tr key={d.sn} onClick={()=>select(d)}><td><div className="device"><span>{d.product}</span><div><b>{d.site}</b><small>{d.sn}</small></div></div></td><td>{d.customer}</td><td><span className={`status ${tone(d.status)}`}><i/>{d.status}</span></td><td><b className={d.days!==null&&d.days<=3?"danger-text":""}>{d.days===null?"—":`${d.days} 天`}</b></td><td>{d.expiry}</td><td><span className={`connection ${d.online?"online":""}`}><i/>{d.online?"在线":"离线"}</span></td><td>{d.mode}</td><td>›</td></tr>)}</tbody></table></div>}

function Devices({rows,query,filter,setQuery,setFilter,select,create}:{rows:Device[];query:string;filter:string;setQuery:(v:string)=>void;setFilter:(v:string)=>void;select:(d:Device)=>void;create:()=>void}){return <><Heading tag="ASSET MANAGEMENT" title="设备资产" sub="查看设备绑定、授权状态、离线计时和锁机策略。" actions={<button className="primary" onClick={create}>＋ 生成 Token</button>}/><section className="panel table-panel full"><div className="toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索设备 SN、站点或客户"/></label><div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>全部状态</option><option>运行中</option><option>即将到期</option><option>已锁定</option><option>时钟异常</option><option>永久解锁</option></select><button className="secondary">更多筛选</button><button className="secondary">导出</button></div></div><div className="result"><b>{rows.length} 台设备</b><span>数据更新时间：2026-07-28 10:42 (UTC+8)</span></div><DeviceTable rows={rows} select={select}/><footer className="pager"><span>显示 1–{rows.length}，共 1,284 台</span><div><button>‹</button><button className="active">1</button><button>2</button><button>3</button><em>…</em><button>129</button><button>›</button></div></footer></section></>}

function Tokens({create,notify}:{create:()=>void;notify:(m:string)=>void}){
  const rows=[["TK-20260728-0184","延期 30 天","CH3ZA26071408","待使用","Peng Li","WhatsApp"],["TK-20260728-0183","永久解锁","CH2ZA26020611","审批中","Thabo M.","邮件"],["TK-20260727-0179","时间修复","CH2ZA26041826","已使用","SAJ Support","现场交付"],["TK-20260727-0174","延期 60 天","CH2ZA26060317","已使用","Nandi K.","SMS"],["TK-20260726-0168","临时解锁 24h","CH3BW26052504","已过期","Peng Li","邮件"]];
  return <><Heading tag="OFFLINE AUTHORIZATION" title="Token 中心" sub="签发与设备唯一绑定的一次性离线授权码，所有操作均可审计。" actions={<button className="primary" onClick={create}>＋ 生成 Token</button>}/><div className="token-stats">{[["本月生成","384","较上月 +12%"],["待使用","27","平均 1.8 天内使用"],["验证成功率","98.7%","重复使用已拦截 9 次"],["被冻结设备","3","连续错误达到阈值"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></div>)}</div><section className="panel token-panel"><div className="toolbar"><label>⌕<input placeholder="搜索 Token 编号或设备 SN"/></label><button className="secondary" onClick={()=>notify("Token 记录已导出")}>导出记录</button></div><div className="simple-table"><header><span>Token 编号</span><span>类型</span><span>绑定设备</span><span>状态</span><span>生成人</span><span>交付渠道</span></header>{rows.map(r=><button key={r[0]} onClick={()=>notify(`${r[0]} 的审计记录已打开`)}>{r.map((c,i)=><span key={c} className={i===3?"token-state":""}>{c}</span>)}</button>)}</div></section></>
}

function Approvals({notify}:{notify:(m:string)=>void}){
  const items=[["永久解锁","Pretoria Medical Centre","CH2ZA26020611","Thabo Mokoena","客户已完成全部 24 期付款，财务凭证已核验。","关键负载项目"],["转租重置","Bloemfontein Warehouse","CH3ZA26011242","Nandi Khumalo","原租赁合同终止，设备将转移至新客户名下。","需要重新绑定"],["时间修复","Lusaka Agro Processing","CH2ZM26041803","SAJ Support","RTC 电池更换后时间基准异常，现场诊断已完成。","宽限期剩余 11h"]];
  return <><Heading tag="CONTROLLED ACTIONS" title="审批中心" sub="永久解锁、转租重置和时间修复等高权限动作必须经过审批。"/><div className="tabs"><button className="active">待我审批 <em>3</em></button><button>我发起的</button><button>已处理</button></div><div className="approvals">{items.map(x=><article className="panel" key={x[2]}><i>✓</i><div><header><span className="status purple">{x[0]}</span><small>2 小时前</small></header><h2>{x[1]}</h2><p className="mono">{x[2]}</p><blockquote>{x[4]}</blockquote><footer><span>申请人 <b>{x[3]}</b></span><span>风险提示 <b>{x[5]}</b></span></footer></div><aside><button className="secondary" onClick={()=>notify("申请已退回补充材料")}>退回</button><button className="primary" onClick={()=>notify(`${x[0]}申请已批准`)}>批准</button></aside></article>)}</div></>
}

function Audit(){const logs=[["今天 10:21:36","Peng Li","生成延期 Token","CH3ZA26071408","授权增加 30 天","成功"],["今天 09:52:08","设备本地","Token 验证","CH2ZA26060317","Token 首次验证","成功"],["今天 09:08:44","系统策略","时间异常告警","CH2ZA26041826","RTC 回拨 18h，进入 72h 宽限","风险"],["昨天 18:42:19","设备本地","重复 Token 拦截","CH3BW26052504","Token 已使用","已拦截"],["昨天 12:00:00","系统策略","设备锁定","CH3BW26052504","授权剩余时间归零","已执行"]];return <><Heading tag="TRACEABILITY" title="审计日志" sub="关键授权变更、异常时间、验证失败和审批动作均不可变更地记录。" actions={<button className="secondary">导出审计包</button>}/><section className="panel audit"><div className="toolbar"><label>⌕<input placeholder="搜索设备、操作人或事件"/></label><select><option>全部事件</option><option>Token 操作</option><option>安全异常</option></select></div>{logs.map(x=><article key={x[0]+x[2]}><i className={x[5]==="风险"?"risk":""}/><time>{x[0]}</time><div><b>{x[2]}</b><p>{x[4]}</p></div><span className="mono">{x[3]}</span><span>{x[1]}</span><em>{x[5]}</em></article>)}</section></>}

function Settings({notify}:{notify:(m:string)=>void}){const [mode,setMode]=useState("B");return <><Heading tag="POLICY CONFIGURATION" title="策略配置" sub="配置项目默认授权周期、锁机方式和安全阈值；变更仅影响新激活设备。" actions={<button className="primary" onClick={()=>notify("策略已保存，变更已写入审计日志")}>保存更改</button>}/><div className="settings"><aside className="panel"><button className="active">授权参数</button><button>锁机策略</button><button>Token 安全</button><button>角色与权限</button><button>消息与交付</button></aside><section className="panel settings-form"><header><div><h2>项目默认策略</h2><p>南部非洲区域 CH3 / CH2 新激活项目</p></div><span className="status success">已启用</span></header><Setting title="授权周期" sub="设备首次激活与普通延期的默认时长。"><div className="field-grid"><label>初始授权期<select><option>7 天（建议）</option><option>30 天</option></select></label><label>普通延期周期<select><option>30 / 60 / 90 天</option></select></label><label className="wide">到期提醒节点<div className="chips"><button>剩余 3 天</button><button>剩余 1 天</button><button>到期当天</button></div></label></div></Setting><Setting title="默认锁机模式" sub="商业限制不能覆盖 BMS、消防、温控等安全保护。"><div className="radio-cards"><label className={mode==="A"?"active":""}><input type="radio" checked={mode==="A"} onChange={()=>setMode("A")}/><span><b>A · 完全停止能源输出</b><small>停止 AC 负载输出及电池放电。</small></span></label><label className={mode==="B"?"active":""}><input type="radio" checked={mode==="B"} onChange={()=>setMode("B")}/><span><b>B · 限制储能服务</b><small>禁止电池放电，可保留电网旁路。</small><em>当前推荐</em></span></label></div></Setting><Setting title="异常与防暴力" sub="防止时间回拨、Token 重放和暴力尝试。"><div className="field-grid"><label>连续输错限制<select><option>5 次</option></select></label><label>输入冻结时长<select><option>10 分钟</option></select></label><label>时钟异常宽限期<select><option>72 小时（建议）</option><option>48 小时</option></select></label><label>断电期间计时<select><option>按自然日继续计时</option></select></label></div></Setting></section></div></>}
function Setting({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <div className="setting"><div><h3>{title}</h3><p>{sub}</p></div>{children}</div>}

function Drawer({device,close,create}:{device:Device;close:()=>void;create:()=>void}){return <div className="backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><aside className="drawer"><header><div><span className={`status ${tone(device.status)}`}>{device.status}</span><h2>{device.site}</h2><p>{device.sn} · {device.product} EMS</p></div><button onClick={close}>×</button></header><div className="drawer-body"><section className="license"><small>剩余授权时间</small><div><b>{device.days===null?"永久":device.days}</b>{device.days!==null&&<span>天</span>}</div><p>授权到期：{device.expiry}</p><i><em style={{width:`${device.days===null?100:Math.max(8,device.days*2)}%`}}/></i></section><section><h3>设备与授权</h3><dl><div><dt>客户</dt><dd>{device.customer}</dd></div><div><dt>设备连接</dt><dd>{device.online?"在线":"离线"}</dd></div><div><dt>电池 SOC</dt><dd>{device.soc}%</dd></div><div><dt>锁机模式</dt><dd>{device.mode}</dd></div><div><dt>本地通道</dt><dd>BLE / 本地 Wi-Fi</dd></div></dl></section><section className="protected"><header><span>✓</span><div><b>安全服务保持运行</b><small>商业锁机不会关闭以下能力</small></div></header><div><span>BMS 保护</span><span>消防与温控</span><span>保护性充电</span><span>本地 Token 输入</span></div></section><section><h3>最近事件</h3><div className="timeline"><p><i/><span><b>授权到期提醒已触发</b><small>今天 08:00</small></span></p><p><i/><span><b>设备状态同步</b><small>2 小时前</small></span></p><p><i/><span><b>项目激活并写入初始授权</b><small>2026-05-25 · Peng Li</small></span></p></div></section></div><footer><button className="secondary" onClick={close}>关闭</button><button className="primary" onClick={create}>生成 Token</button></footer></aside></div>}

function TokenModal({token,close,generate}:{token:string;close:()=>void;generate:()=>void}){const [type,setType]=useState("延期 Token");return <div className="modal-bg" onMouseDown={e=>e.currentTarget===e.target&&close()}><section className="modal"><header><div><small>OFFLINE AUTHORIZATION</small><h2>生成离线 Token</h2><p>Token 与指定设备绑定，仅可成功使用一次。</p></div><button onClick={close}>×</button></header>{!token?<><div className="modal-body"><div className="notice"><b>◇</b><span><strong>设备侧离线验证</strong><small>设备无需联网，请通过受信任渠道交付。</small></span></div><label>设备 SN / 站点<input defaultValue="CH3ZA26071408 — Cape Town Cold Storage"/></label><label>Token 类型<select value={type} onChange={e=>setType(e.target.value)}><option>延期 Token</option><option>指定日期 Token</option><option>临时解锁 Token</option><option>永久解锁 Token（需审批）</option><option>时间修复 Token（需审批）</option></select></label><div className="two"><label>授权周期<select><option>30 天</option><option>60 天</option><option>90 天</option></select></label><label>交付渠道<select><option>WhatsApp</option><option>SMS</option><option>邮件</option></select></label></div><label>生成原因<textarea defaultValue="客户 7 月账期付款已确认到账。"/></label>{type.includes("需审批")&&<div className="approval-warning">此类 Token 需管理员审批后才能签发。</div>}</div><footer><button className="secondary" onClick={close}>取消</button><button className="primary" onClick={generate}>{type.includes("需审批")?"提交审批":"确认生成"}</button></footer></>:<div className="token-result"><span>✓</span><h3>Token 已生成</h3><p>延期 30 天 · CH3ZA26071408</p><div>{token}</div><small>一次性使用 · 与设备唯一绑定</small><button className="primary" onClick={close}>完成</button></div>}</section></div>}
